spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prod_db2?serverTimezone=Asia/Seoul
    username: root
    password: final1234
#    url: jdbc:mysql://playdata.cqro5qdbxzm7.ap-northeast-2.rds.amazonaws.com:3306/summermart?serverTimezone=Asia/Seoul
#    username: admin
#    password: "qwer1234!"


  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true

